### Importation des données

In [1]:
import sys
sys.path.append('../src')
import utils
import pandas as pd
import s3fs
import geopandas as gpd

Notre première base de données correspond aux arbres dans la ville de Paris.

In [4]:
arbres = pd.read_csv("https://www.data.gouv.fr/api/1/datasets/r/60433484-f30e-44ef-a362-e5553a9b7a42", sep = ";")

In [10]:
arbres

,IDBASE,TYPE EMPLACEMENT,DOMANIALITE,ARRONDISSEMENT,COMPLEMENT ADRESSE,LIEU / ADRESSE,IDEMPLACEMENT,LIBELLE FRANCAIS,GENRE,ESPECE,VARIETE OUCULTIVAR,CIRCONFERENCE (cm),HAUTEUR (m),STADE DE DEVELOPPEMENT,REMARQUABLE,geo_point_2d,lat,lon
0,267615,Arbre,Alignement,PARIS 1ER ARRDT,4 f,QUAI FRANCOIS MITTERRAND,000101033,Platane,Platanus,x hispanica,NaN,322,20,Adulte,NON,"48.85936815146502, 2.336197260919396",48.859368,2.336197
1,2001356,Arbre,Alignement,BOIS DE BOULOGNE,Candélabre n°7281,ALLEE DE LA REINE MARGUERITE,001202097,Marronnier,Aesculus,hippocastanum,NaN,161,15,Adulte,NON,"48.87256400936489, 2.254016470558061",48.872564,2.254016
2,2015583,Arbre,Jardin,BOIS DE VINCENNES,NaN,PARC FLORAL DE PARIS / ROUTE DE LA PYRAMIDE,02910005,Magnolia,Magnolia,grandiflora,NaN,80,8,Adulte,NON,"48.837160227435746, 2.4439083626402907",48.837160,2.443908
3,2021315,Arbre,DASCO,PARIS 20E ARRDT,NaN,ECOLE MATERNELLE / 20 RUE DES CENDRIERS,063902002,Poirier à fruits,Pyrus,communis,''Doyenné du Comice'' COMICE,20,2,Jeune (arbre),NON,"48.86520599592482, 2.3867746391040847",48.865206,2.386775
4,2054405,Arbre,Alignement,PARIS 13E ARRDT,NaN,PLACE NATIONALE,000304001,Tilleul,Tilia,x europaea,NaN,35,5,Jeune (arbre),NON,"48.82951463924067, 2.365357007521199",48.829515,2.365357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217747,283255,Arbre,Alignement,PARIS 19E ARRDT,NaN,PLACE DE JOINVILLE,000101006,Platane,Platanus,x hispanica,NaN,55,7,Jeune (arbre)Adulte,NON,"48.88963327830016, 2.380303666095808",48.889633,2.380304
217748,2024286,Arbre,Jardin,BOIS DE VINCENNES,L-08,ARBORETUM DE PARIS / 50 ROUTE DE LA PYRAMIDE,05-719480719,Cèdre,Cedrus,atlantica,''Atlantica Pendula'',0,0,NaN,NON,"48.82132687128179, 2.457343421639024",48.821327,2.457343
217749,261246,Arbre,Alignement,PARIS 17E ARRDT,NaN,RUE CURNONSKY,000202001,Erable,Acer,platanoides,''Globosum'',33,3,Jeune (arbre),NON,"48.89093410862582, 2.2971646942176833",48.890934,2.297165
217750,232032,Arbre,Alignement,PARIS 19E ARRDT,NaN,RUE DE BELLEVILLE,000103011,Sophora,Styphnolobium,japonicum,NaN,120,10,Adulte,NON,"48.87537993953184, 2.394283352566337",48.875380,2.394283
217751,236758,Arbre,Alignement,PARIS 17E ARRDT,NaN,PASSAGE PETIT CERF,000201005,Tilleul,Tilia,cordata,NaN,83,6,Adulte,NON,"48.89373951705164, 2.3172816460399415",48.893740,2.317282

Notre deuxième base de données correspond aux iris de Paris, triés depuis les iris de la France métropolitaine.

In [5]:
fs = s3fs.S3FileSystem(client_kwargs={"endpoint_url": "https://minio.lab.sspcloud.fr"})

MY_BUCKET = "raphcrre"
PATH_IRIS = f"{MY_BUCKET}/diffusion/projet_arbres/iris.gpkg"

with fs.open(PATH_IRIS, 'rb') as f:
    iris_france = gpd.read_file(f)

iris = iris_france[iris_france['code_insee'].astype(str).str.startswith('75')].copy()

/opt/python/lib/python3.13/site-packages/pyogrio/raw.py:200: RuntimeWarning: File /vsimem/pyogrio_bbf90be8b6d44c22a7563836fd97230a has GPKG application_id, but non conformant file extension
  return ogr_read(

In [7]:
iris

,cleabs,code_insee,nom_commune,iris,code_iris,nom_iris,type_iris,geometry
99,IRIS____0000000751010102,75101,Paris 1er Arrondissement,0102,751010102,Saint-Germain l'Auxerrois 2,A,"MULTIPOLYGON (((652048.7 6861993.1, 652000.9 6..."
137,IRIS____0000000751010103,75101,Paris 1er Arrondissement,0103,751010103,Saint-Germain l'Auxerrois 3,A,"MULTIPOLYGON (((651639.9 6862521.6, 651869 686..."
176,IRIS____0000000751010104,75101,Paris 1er Arrondissement,0104,751010104,Saint-Germain l'Auxerrois 4,A,"MULTIPOLYGON (((651514.6 6862585.4, 651639.9 6..."
446,IRIS____0000000751010205,75101,Paris 1er Arrondissement,0205,751010205,Les Halles 5,A,"MULTIPOLYGON (((652198.8 6862680.2, 652146.4 6..."
449,IRIS____0000000751010206,75101,Paris 1er Arrondissement,0206,751010206,Les Halles 6,A,"MULTIPOLYGON (((651670.6 6863058.7, 651808.1 6..."
...,...,...,...,...,...,...,...,...
15577,IRIS____0000000751208022,75120,Paris 20e Arrondissement,8022,751208022,Charonne 22,H,"MULTIPOLYGON (((656411.5 6862589, 656445.6 686..."
15578,IRIS____0000000751208023,75120,Paris 20e Arrondissement,8023,751208023,Charonne 23,H,"MULTIPOLYGON (((656511.6 6862331, 656434.9 686..."
15579,IRIS____0000000751208024,75120,Paris 20e Arrondissement,8024,751208024,Charonne 24,H,"MULTIPOLYGON (((656034.7 6861937.3, 655928.7 6..."
15580,IRIS____0000000751208025,75120,Paris 20e Arrondissement,8025,751208025,Charonne 25,H,"MULTIPOLYGON (((655877.3 6861839.9, 655832.6 6..."
15581,IRIS____0000000751208026,75120,Paris 20e Arrondissement,8026,751208026,Charonne 26,H,"MULTIPOLYGON (((655681.7 6861757.5, 655561.2 6..."

Réalisons une jointure entre nos tables pour avoir les informations sur les iris de chaque arbre.

In [ ]:
df_arbres = utils.jointure_arbres_iris(arbres, iris)

df_arbres

,IDBASE,TYPE EMPLACEMENT,DOMANIALITE,ARRONDISSEMENT,COMPLEMENT ADRESSE,LIEU / ADRESSE,IDEMPLACEMENT,LIBELLE FRANCAIS,GENRE,ESPECE,...,lon,geometry,index_right,cleabs,code_insee,nom_commune,iris,code_iris,nom_iris,type_iris
0,267615,Arbre,Alignement,PARIS 1ER ARRDT,4 f,QUAI FRANCOIS MITTERRAND,000101033,Platane,Platanus,x hispanica,...,2.336197,POINT (651297.47 6862352.805),1010.0,IRIS____0000000751010199,75101,Paris 1er Arrondissement,0199,751010199,Seine et Berges,D
1,2001356,Arbre,Alignement,BOIS DE BOULOGNE,Candélabre n°7281,ALLEE DE LA REINE MARGUERITE,001202097,Marronnier,Aesculus,hippocastanum,...,2.254016,POINT (645281.981 6863873.891),1131.0,IRIS____0000000751166277,75116,Paris 16e Arrondissement,6277,751166277,Bois de Boulogne 2,D
2,2015583,Arbre,Jardin,BOIS DE VINCENNES,NaN,PARC FLORAL DE PARIS / ROUTE DE LA PYRAMIDE,02910005,Magnolia,Magnolia,grandiflora,...,2.443908,POINT (659182.59 6859822.43),1117.0,IRIS____0000000751124577,75112,Paris 12e Arrondissement,4577,751124577,Bois de Vincennes 1,D
3,2021315,Arbre,DASCO,PARIS 20E ARRDT,NaN,ECOLE MATERNELLE / 20 RUE DES CENDRIERS,063902002,Poirier à fruits,Pyrus,communis,...,2.386775,POINT (655013.244 6862971.921),15545.0,IRIS____0000000751207906,75120,Paris 20e Arrondissement,7906,751207906,Père Lachaise 6,H
4,2054405,Arbre,Alignement,PARIS 13E ARRDT,NaN,PLACE NATIONALE,000304001,Tilleul,Tilia,x europaea,...,2.365357,POINT (653410.164 6859015.797),15037.0,IRIS____0000000751135030,75113,Paris 13e Arrondissement,5030,751135030,Gare 30,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217747,283255,Arbre,Alignement,PARIS 19E ARRDT,NaN,PLACE DE JOINVILLE,000101006,Platane,Platanus,x hispanica,...,2.380304,POINT (654559.854 6865691.787),15455.0,IRIS____0000000751197314,75119,Paris 19e Arrondissement,7314,751197314,Villette 14,H
217748,2024286,Arbre,Jardin,BOIS DE VINCENNES,L-08,ARBORETUM DE PARIS / 50 ROUTE DE LA PYRAMIDE,05-719480719,Cèdre,Cedrus,atlantica,...,2.457343,POINT (660156.615 6858055.064),1118.0,IRIS____0000000751124677,75112,Paris 12e Arrondissement,4677,751124677,Bois de Vincennes 2,D
217749,261246,Arbre,Alignement,PARIS 17E ARRDT,NaN,RUE CURNONSKY,000202001,Erable,Acer,platanoides,...,2.297165,POINT (648465.006 6865887.484),15334.0,IRIS____0000000751176616,75117,Paris 17e Arrondissement,6616,751176616,Plaine Monceau 16,H
217750,232032,Arbre,Alignement,PARIS 19E ARRDT,NaN,RUE DE BELLEVILLE,000103011,Sophora,Styphnolobium,japonicum,...,2.394283,POINT (655572.757 6864098.942),15474.0,IRIS____0000000751197505,75119,Paris 19e Arrondissement,7505,751197505,Amérique 5,H
217751,236758,Arbre,Alignement,PARIS 17E ARRDT,NaN,PASSAGE PETIT CERF,000201005,Tilleul,Tilia,cordata,...,2.317282,POINT (649942.73 6866186.489),15363.0,IRIS____0000000751176813,75117,Paris 17e Arrondissement,6813,751176813,Épinettes 13,H